### ISSUE TITLE
Run all classes through a formatter

### ISSUE THREAD

**Issue by halfer** [angelleye/paypal-php-library#100]
It looks like you're using tab indents here. That's fine, it does not matter whether you use tabs/spaces, as long as it is consistent. However [some methods like this one](https://github.com/angelleye/paypal-php-library/blob/dev/src/angelleye/PayPal/Financing.php#L95) have indentation problems in their docblocks and/or their body.

These can be repaired using the formatting tool in an IDE.

**Comment by angelleye** [comment]
Thanks for all your feedback and creating issues.  I've added each to our 3.0 milestone.  We'll be working on getting this released before long.

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/PPCL-101
