### ISSUE TITLE
Demo Kits - Home Page adjustment

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-php-library#103]
The intro/home page for the demo kits has every demo kit lined up like a product.  now that we have REST included, though, I'd like to separate these.

So the demo kit intro/home page could have toggles where you click to view "Classic" or "REST" and it'll only show those options.  A number of ways we could do this of course.  Just want it to look nice and clean / professional.

**Comment by angelleye** [comment]
Should also probably separate Free and Paid demo kits.  We can include Basic EC and Basic Pro for free, but the rest would be paid.

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/PPCL-98
