### ISSUE TITLE
Make CURLOPT_VERBOSE as optional

### ISSUE THREAD

**Issue by devbazilio** [angelleye/paypal-php-library#107]
I'm running script via cron job and see in output a lot of debug data.
Please make this option curl_setopt($curl, CURLOPT_VERBOSE, $this->Sandbox); as optional

**Comment by angelleye** [comment]
Thanks for the feedback, we'll see about this getting this done.

**Comment by angelleye** [comment]
@tejasm-itpath We should be able to add this option to our config.php file (and sample) and then add it to the $PayPalConfig array that we're passing into our $PayPal object.

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/PPCL-95
