### ISSUE TITLE
CURRENCYCODE missig in TransactionSearch

### ISSUE THREAD

**Issue by asif-rahman** [angelleye/paypal-php-library#110]
Hi, I'm currently working with TransactionSearch API. The SEARCHRESULTS array is a great element there to iterate over items. But unfortunately, CURRENCYCODE is missing on each element although L_CURRENCYCODE0, L_CURRENCYCODE1 are there in the main array. Have any work around to get this?

**Comment by angelleye** [comment]
Thanks for the feedback.  I'll have to look into that and make necessary adjustments in the main class file.  We're working to get this 3.0 release done before long, and I'll be sure to get this included.

**Comment by tejasm-itpath** [comment]
@angelleye  @asif-rahman 
1 ) You will get Currency Code when Transaction Status is 
**Completed or Placed or Under Review**
2 ) You will **NOT** get Currency Code when Transaction Status is 
**Canceled or Created**

**Comment by asif-rahman** [comment]
Nope. You are not right. The currency codes are present in the original
response in the form of L_CURRENCYCODE0, 1, 2 etc.

Regards,
Asif Rahman

**Comment by tejasm-itpath** [comment]
@asif-rahman  I have added one commit , You can pull this commit and run it. 
PayPal is sending L_CURRENCYCODEn as blank while status is Canceled or Created.

**Comment by asif-rahman** [comment]
Ok I'll try. Thanks.

Regards,
Asif Rahman

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/PPCL-93
