### ISSUE TITLE
PHONENUM missing from GetTransactionDetails

### ISSUE THREAD

**Issue by cnvhu** [angelleye/paypal-php-library#113]
Hi,
I try to get details for existing transactions using GetTransactionDetails.
Most data are there, but PHONENUM is missing (in PayPal I can see phone numbers, but GetTransactionDetails does not return them).
When I last checked this library more than a year ago, this was working as far as I remember.
As I see now, the GetTransactionDetails API NVP field set has changed a lot since (also, they are already at v204.0 instead of 119) and now they call it SHIPTOPHONENUM, but that field is also not contained in the transaction details.

**Comment by angelleye** [comment]
Actually, it should be coming back in the payment array within the response.  Can you provide a full sample of a response you're getting?

**Comment by cnvhu** [comment]
Thanks for the quick reaction!
Is it okay if I send the RAWRESPONSE contents?
(I would alter customer data but leave the structure intact)

**Comment by angelleye** [comment]
Yes please do.

**Comment by cnvhu** [comment]
(I checked a number of different transactions, all of which have customer phone number in PayPal transaction details, but none of them are returned in the rawresponse.)

**Comment by angelleye** [comment]
Do you have the request log that generated this payment so we can see if it included the phone number there?  Also, can you provide a screenshot of the phone number on the transaction details page in PayPal (with data blurred)?

**Comment by cnvhu** [comment]
I have turned on the logging and requested some data again.
In the log files, there are also no fields that contain "phone" substring, or any part of the actual phone numbers. So, is it a paypal API error?

I attached a screenshot of the paypal tx details page.
It shows the phone number in the usual place, like in all other transactions, so I guess that is okay.

![paymentdetails_blurred](https://user-images.githubusercontent.com/31868222/30344961-a6583678-9803-11e7-9652-52e1a13f8972.jpg)

**Comment by angelleye** [comment]
Oh, I just realized these are eBay payments, so you're not the one sending the payment request to PayPal.  Yeah, I think this is a problem on PayPal's end.  I will bring it up to my PayPal tech support rep and see what they can tell us.

Can you verify the transaction ID included in the sample above is the actual one for this transaction:  1728723591021?  Or did you change that when you posted the response log?

**Comment by cnvhu** [comment]
I changed the transaction number.
Do you need the original one(s) as reference for PayPal support?

**Comment by cnvhu** [comment]
Can I maybe use another method to get the phone numbers?
Like, GetBasicPersonalData or GetAdvancedPersonalData?

And an offtopic question:
Is there a way to change paypal order status to SHIPPED and add tracking number through this library?
(I did not find it in sample codes, but who knows...)

**Comment by angelleye** [comment]
For what you're doing it will probably be best to use eBay APIs to pull that sort of buyer detail.

**Comment by angelleye** [comment]
Unfortunately, PayPal has no way to update shipping details via the API.  I've been begging for it for years and it just hasn't made their list for some reason.

**Comment by cnvhu** [comment]
Okay, thank you very much for the information.
Also thanks for the great work with this library.
Wish you all the best!

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/PPCL-90
