### ISSUE TITLE
Add support to PayPal Payouts API

### ISSUE THREAD

**Issue by loreboldo** [angelleye/paypal-php-library#115]
As of now, both Adaptive Payments and Masspay are either on a limited release or deprecated. 
[Payouts](https://developer.paypal.com/docs/integration/direct/payouts/integration-guide/payouts_api/) is the PayPal's recommended alternative.
Can you please add support for this API as well?

Thank you very much for your wonderful job.

**Comment by angelleye** [comment]
@loreboldo I'm sorry for the delay responding.  We actually have that already included in our dev branch.  I'm just behind on getting all of the new stuff merged and released officially.  All of the REST APIs are now included as samples/templates, though.
