### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Jacksonhogan01** [angelleye/paypal-php-library#117]
I get this error when I try and open the php file CreateAndSendInvoice.php

Fatal error: Class 'angelleye\PayPal\Adaptive' not found in /home/crysuicn/admin.crystaldev.net/samples/CreateAndSendInvoice.php on line 23

Line 23: $PayPal = new angelleye\PayPal\Adaptive($PayPalConfig);

**Comment by Jacksonhogan01** [comment]
I am using 5.6

**Comment by Jacksonhogan01** [comment]
I am using PHP version 5.6

**Comment by tejasm-itpath** [comment]
@Jacksonhogan01  
Are you using composer ? 
I am thinking that you have not added corrected path for the namespace.

**Comment by Jacksonhogan01** [comment]
The namespace in Adaptive.php is angelleye/PayPal

**Comment by tejasm-itpath** [comment]
@Jacksonhogan01 
Yes that's correct. 
Are you using composer ? Please check the path for autoload.php

**Comment by Jacksonhogan01** [comment]
I am not using composer. The path for autoload is good.

**Comment by angelleye** [comment]
@Jacksonhogan01 Well, for one reason or another it's not finding the classes, but of course the classes do exist in the library.  This could happen on PHP versions prior to 5.3 since that's when  namespaces was introduced, but you said you're on 5.6 so that shouldn't be the problem.  The only other thing to check would be the path, so...please double check that.

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/PPCL-89

**Comment by EL34xyz** [comment]
The install paths with composer do not match the folder structure I see in the youtube install videos.
I can't seem to get Angell to send me a screen shot showing the exact folder layout

**Comment by angelleye** [comment]
@EL34xyz The video is out-dated, but the documentation page is updated.  Have you checked here?  https://www.angelleye.com/install-angell-eye-php-class-library-paypal/

It shows the new version being used, and it shows the structure of this version with screenshots.

Let me know if you're still struggling with this after reviewing that.

**Comment by EL34xyz** [comment]
Why wouldn't you have the correct composer.json in your file download here on github?

**Comment by angelleye** [comment]
The GitHub repo you are looking at is for the packaged library itself.  These contain more info in their composer.json file to make it work with Composer/Packagist in general.

When you install the library into an actual project, you use the simplified composer.json for that project.
