### ISSUE TITLE
Question about custom fees

### ISSUE THREAD

**Issue by dyanakiev** [angelleye/paypal-php-library#118]
Hello,

Currently i have stripe integration in my site where when someone buy something the money for the product goes to one person and then we have custom booking fee that goes to our account.

Is there easy way to the same thing with paypal?

**Comment by angelleye** [comment]
As you mentioned in the other ticket, you can use Parallel Payments for this.  I have a [more detailed article](https://www.angelleye.com/paypal-split-payments-express-checkout-billing-agreements-reference-transactions/) on additional options as well.
