### ISSUE TITLE
PayFlow Express Checkout

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-php-library#12]
Need to get templates setup for PayFlow gateway Express Checkout flow.

We can use our own PayFlow template, of course, and we'll just need to setup all the calls necessary to complete the Express Checkout flow outlined in this documentation:  https://www.paypalobjects.com/webstatic/en_US/developer/docs/pdf/pfp_expresscheckout_pp.pdf

Our template / sample names can be PayFlow_SetExpressCheckout.php, PayFlow_GetExpressCheckoutDetails.php, PayFlow_DoExpressCheckoutPayment.php, etc.

**Comment by keyurptl** [comment]
we'll do this in a demo kit

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/PPCL-121
