### ISSUE TITLE
Adaptive live Payment Not working

### ISSUE THREAD

**Issue by naime-hossain** [angelleye/paypal-php-library#150]
I use these data for live Version but giving an error.
Internal Error.
PAYPAL_LIVE_API_USERNAME=
PAYPAL_LIVE_API_PASSWORD=
PAYPAL_LIVE_API_SECRET=
PAYPAL_LIVE_API_CERTIFICATE=
May i know what i am missing?

**Comment by iMansoorAliKhan** [comment]
Hi @naime-hossain ,

We have received your request and one of our experts will look into that and reply you soon.

Thanks!

**Comment by angelleye** [comment]
@naime-hossain That doesn't look correct.  Please provide a copy of what you're doing in the config file and I'll help you format it properly.

**Comment by naime-hossain** [comment]
I am using laravel. and this is the .env file info for PayPal adaptive.

#PayPal Setting & API Credentials - sandbox
PAYPAL_SANDBOX_API_USERNAME=
PAYPAL_SANDBOX_API_PASSWORD=
PAYPAL_SANDBOX_API_SECRET=
PAYPAL_SANDBOX_API_CERTIFICATE=
PAYPAL_SANDBOX_API_APPID=
SANDBOX_CLIENT_ID=
SANDBOX_SECRET_ID=


#PayPal Setting & API Credentials - live


PAYPAL_LIVE_API_USERNAME=
PAYPAL_LIVE_API_PASSWORD=
PAYPAL_LIVE_API_SECRET=
PAYPAL_LIVE_API_CERTIFICATE=

**Comment by angelleye** [comment]
It's actually been a while since I've set this in Laravel myself, but looking at my previous projects this is how I had it configured:

```
return array(

    'PAYPAL_SANDBOX' => true,
    'PAYPAL_API_USERNAME' => 'sandbo_1215254764_biz_api1.angelleye.com',
    'PAYPAL_API_PASSWORD' => '1215254774',
    'PAYPAL_API_SIGNATURE' => 'AiKZhEEPLJjSIccz.2M.tbyW5YFwAb6E3l6my.pY9br1z2qxKx96W18v'

);
```

So you really want to set `PAYPAL_API_USERNAME`, `PAYPAL_API_PASSWORD`, and `PAYPAL_API_SIGNATURE`, with `PAYPAL_SANDBOX` flagging which API endpoints it should use.

Then inside my PayPal model, I have this:

```
    /**
     * Constructor
     */
    public function __construct(){
        $this->PayPal = new \angelleye\PayPal\PayPal($this->getPayPalConfig());
    }

    /**
     * @return array
     *
     * Get an array of config data to pass into PayPal API request methods.
     */
    private function getPayPalConfig()
    {
        return array(
            'Sandbox' => Config::get('paypal.sandbox'),
            'APIUsername' => Config::get('paypal.api-username'),
            'APIPassword' => Config::get('paypal.api-password'),
            'APISignature' => Config::get('paypal.api-signature')
        );
    }
```

Does that help?

**Comment by naime-hossain** [comment]
In sandbox its works fine but in live its not working and paypal said they dont support adaptive payment :(

**Comment by iMansoorAliKhan** [comment]
Hi @naime-hossain  Thanks for writing us here. We are looking into this and will get back to you asap.
Thanks!

@angelleye Please look at this when you are online.
Thank you!

**Comment by angelleye** [comment]
@naime-hossain  Sorry, I didn't notice above where you mentioned Adaptive.  Unfortunately, PayPal is no longer approve live apps for Adaptive.  

What exactly is your goal with the payment?  I might be able to give you a different path towards it.

**Comment by naime-hossain** [comment]
This is Project to make payment system for crowdFunding Application.
Thanks

**Comment by iMansoorAliKhan** [comment]
Hi @naime-hossain Thanks for writing us here. We are looking into this and will get back to you asap.
Thanks!

@angelleye Please look at this when you are online.
Thank you!

**Comment by angelleye** [comment]
@naime-hossain Sorry again for the delay replying.

The best thing for you would be the PayPal for Partners platform.  Unfortunately, it's not available yet.

Until then, you might get some info you can use from this article:  https://www.angelleye.com/paypal-split-payments-express-checkout-billing-agreements-reference-transactions/
