### ISSUE TITLE
Class 'PayPal\Common\PayPalModel' not found

### ISSUE THREAD

**Issue by chouckz** [angelleye/paypal-php-library#177]
When using REST API sample CreateInvoice.php
getting error "Fatal error: Class 'PayPal\Common\PayPalModel' not found in .../src/angelleye/PayPal/RestClass.php on line 44"
all paths are correct

**Comment by EL34xyz** [comment]
I get the same thing. When installing with composer, nothing in the folder tree looks like the examples on youtube.
I can't seem to get any info from Angell on exactly what the directory structure is supposed to loom like.

**Comment by angelleye** [comment]
@EL34xyz I want to help you, but it doesn't help me to help you when you post the same things in multiple places within all of our existing channels.  I've replied to you in a few other places already now about how to try and move forward here.  Let's pick one and stick to that please.

**Comment by EL34xyz** [comment]
Why wouldn't you have the correct composer.json in your file download here on github?
