### ISSUE TITLE
create invoice shipping costs error

### ISSUE THREAD

**Issue by chouckz** [angelleye/paypal-php-library#178]
in order to set proper shipping costs in invoice you need to correct line 249 in src\angelleye\PayPal\rest\invoice\InvoiceAPI.php
it is
 $this->setArrayToMethods(array_filter($requestData['shippingCost']['Currency']), $shippingCurrency);
it should be                        
 $this->setArrayToMethods(array_filter($requestData['shippingCost']['**Amount**']), $shippingCurrency); 
and the following can be added to the samples:
 $shippingCost = array(
        'type' => 'Amount',
        'Amount' => array (
                    'Currency' => 'USD',
                    'Value' => '20'
        ));	 
$requestData =array(
 ...
	'shippingCost'              => $shippingCost,
...
);

you are welcome

**Comment by iMansoorAliKhan** [comment]
Hi @chouckz ,

Thanks for writing us here, we are looking into it and will get back to you asap.

Thanks!
AngellEYE Customer Care

**Comment by iMansoorAliKhan** [comment]
Moved to Jira : PPCL-206

**Comment by dayallnash** [comment]
This appears to be resolved. Can somebody verify?

**Comment by iMansoorAliKhan** [comment]
@dayallnash 

Yeah this ws done 7months ago. Did you checked?

Please check that and et me know if there will still be any concerns
Thanks!
Mansoor


*Mansoor Khan*
Angell EYE Customer Support Specialist
[www.angelleye.com](https://www.angelleye.com) | [Join Our Newsletter](https://www.angelleye.com/newsletter-signup/?utm_source=email&utm_medium=signature&utm_campaign=email_signature)
[Subscribe to Our YouTube Channel](https://www.youtube.com/user/angelleyeconsulting) | [Like Our Facebook Page](https://facebook.com/angelleyeconsulting/)
