### ISSUE TITLE
Payment Services Directive (PSD2) Law

### ISSUE THREAD

**Issue by straightlight** [angelleye/paypal-php-library#195]
Hi,

Are your PayPal SDK libraries (src folder) compliant with the Payment Services Directive (PSD2) law? PayPal have been sending email notes that all EU users processing credit card transactions must be compliant with PSD2 while using 3D Secure with the DoDirectPayment method.

Here's a heads up about it: https://forum.opencart.com/viewtopic.php?f=2&p=753624#p751941

Thanks,

**Comment by angelleye** [comment]
Our libraries allow you to make all the API calls necessary, yes.  We're in the processing of putting together lots of tutorials about how to accomplish specific tasks using various API calls and workflows, and this will be included there.
