### ISSUE TITLE
[Release Branch] - paypal-php-library/blob/release/templates/classic/DoDirectPayment.php

### ISSUE THREAD

**Issue by straightlight** [angelleye/paypal-php-library#196]
In this file,

replace:

`'authstatus3d' => '',`

with:

`'authstatus3ds' => '',`

Then, find:

`'OrderItems' => $OrderItems`

replace with:

'OrderItems' => $OrderItems,
'Secure3D'    => $Secure3D,

**Comment by straightlight** [comment]
Parameter to be replaced as per this documentation: https://developer.paypal.com/docs/classic/paypal-payments-pro/integration-guide/security-features/#3-d-secure-fields-for-direct-payment-transaction-requests

**Comment by angelleye** [comment]
Thanks for the feedback!  We'll take a look and update accordingly.

**Comment by angelleye** [comment]
We got this merged into our release branch, and it will be included in the next official release coming soon.
