### ISSUE TITLE
config.php path issue

### ISSUE THREAD

**Issue by EL34xyz** [angelleye/paypal-php-library#205]
Why do the samples and templates refer to a path that does not exist?
Example in the CreateInvoice.php file
require_once('../../../includes/config.php');

There is no includes folder in the current release that I just downloaded?

**Comment by iMansoorAliKhan** [comment]
@EL34xyz 

Please see this
![image](https://user-images.githubusercontent.com/11312949/60156546-3d77d500-9806-11e9-840a-7a7fc6d0236d.png)

Thanks!
Mansoor


*Mansoor Khan*
Angell EYE Customer Support Specialist
[www.angelleye.com](https://www.angelleye.com) | [Join Our Newsletter](https://www.angelleye.com/newsletter-signup/?utm_source=email&utm_medium=signature&utm_campaign=email_signature)
[Subscribe to Our YouTube Channel](https://www.youtube.com/user/angelleyeconsulting) | [Like Our Facebook Page](https://facebook.com/angelleyeconsulting/)

**Comment by EL34xyz** [comment]
Yes, I did that yesterday
I put my edited config.php in the same folder as the autoload.php
And I edited the test file below like this

```
<?php
// Include required library files.
require_once('../../../autoload.php');
require_once('../../../config.php');
```

I am using a copy of one the samples to create a test invoice because it has all the fields filled out already
I blanked out my real server name in the examples below
https://myserver.com/php/paypal-php-library-master/paypal-php-library-master/samples/rest/invoice/CreateInvoice2.php

I edited the file above with the email from my sandbox account

```// Merchant information is Required for creating new Invoice.
$merchantInfo = array(
    'Email' => 'hoffmanpaypal-facilitator_api1.citcom.net',             // The merchant email address. Maximum length is 260 characters.
    'FirstName' => 'paypal',                                            // The merchant first name. Maximum length is 30 characters.
    'LastName'  => 'facilitator',                                         // The merchant last name. Maximum length is 30 characters.
    'BusinessName' => 'facilitator \'s Test Store',                     // The merchant company business name. Maximum length is 100 characters.
    'Website' => 'https://hoffmanamps.com.com/',                      // The merchant website. Maximum length is 2048 characters.
    'TaxId' => 'P87904347',                                         // The merchant tax ID. Maximum length is 100 characters. 
    'AdditionalInfoLabel' => 'Business hours 10:00 AM to 7:30 PM.'  // Any additional information, such as business hours. 40 characters max. 
);
```

When I run the file above I get this error
Fatal error: Class 'PayPal\Common\PayPalModel' not found in C:\inetpub\vhosts\myserver.com\httpdocs\php\paypal-php-library-master\paypal-php-library-master\src\angelleye\PayPal\RestClass.php on line 45

This is the code section from RestClass.php on line 45

```
use PayPal\Common\PayPalModel;
/**
 * RestClass
 * This class includes the common configuration functions for the REST APIs bridge classes.
 *
 * @package 		paypal-php-library
 * @author			Andrew Angell <service@angelleye.com>
 */

class RestClass extends PayPalModel
{
    /**
     * Private vairable to fetch and return @PayPal\Rest\ApiContext object.
     *
     * @var \PayPal\Rest\ApiContext $_api_context 
     */
    private $_api_context;
```

**Comment by EL34xyz** [comment]
Also note that when I try and run one of the included demos, I get the same exact error

![pp2](https://user-images.githubusercontent.com/16766383/60196154-83369c80-980a-11e9-8460-513aa3195185.png)

**Comment by angelleye** [comment]
@EL34xyz  It looks like you haven't run `composer update` in the directory.  That will install the library.  I don't see the /composer directory in your screenshot.

**Comment by EL34xyz** [comment]
Thanks Drew
I thought I was following the instructions?

It says this in the **README.md** file

It does not say I had to install using composer?
And so I did the manual install,which says to upload the files to the server
Are the instructions not correct?

------------------------------------------------------------------------------

> **Composer Install**
> Create a composer.json file with the following section and run composer update.
> 
>     "require": {
> 		"php": ">=5.3.0",
> 		"ext-curl": "*",
> 		"angelleye/paypal-php-library": "3.0.*"
> 	}

> **Manual Install (without Composer)**
> Download the class library and extract the contents do a directory in your project structure.
> Upload the files to your web server.

**Comment by angelleye** [comment]
I guess I'll have to double check that and make sure the manual install is working as expected.  It's always recommended to use Composer in general, though.  Sorry for any confusion.
