### ISSUE TITLE
UNSUPPORTED_MEDIA_TYPE on dispute action "provide evidence" as merchant

### ISSUE THREAD

**Issue by g33kme** [angelleye/paypal-php-library#210]
Hello,

I get the following error when trying to do the action "**provide evidence**" on **customer disputes as merchant.** I tried on a production dispute case. 

I get the following back from Paypal:

```
Array
(
    [RESULT] => Error
    [error_type] => UNSUPPORTED_MEDIA_TYPE
    [error_message] => The server does not support the request payload’s media type.
    [error_data] => UNSUPPORTED_MEDIA_TYPE
    [error_description] => The server does not support the request payload’s media type
    [debug_id] => d181387b463af
    [information_link] => https://developer.paypal.com/docs/api/customer-disputes/#errors
    [error_array] => Array
        (
            [name] => UNSUPPORTED_MEDIA_TYPE
            [debug_id] => d181387b463af
            [message] => The server does not support the request payload’s media type
            [information_link] => https://developer.paypal.com/docs/api/customer-disputes/#errors
        )

)
```

Any idea whats the problem?

**Comment by devchristina2** [comment]
Hi @g33kme,

Thank you for reaching out and submitting an issue on our GitHub repository.

We wanted to inform you that we’ve temporarily paused active support for this repository and will close all open issues, including this one. If you require further assistance or have additional questions, please submit a support ticket through our [Help Center](https://angelleye.atlassian.net/servicedesk/customer/portals), where our support team will be happy to assist you.

We appreciate your understanding and apologize for any inconvenience. Thank you for being part of our community!

Thanks, Christina.
