### ISSUE TITLE
Manual Install Classic works but using  REST Payments\PaymentAPI Class not found

### ISSUE THREAD

**Issue by dan-lutd** [angelleye/paypal-php-library#211]
This is a manual Install on a Wordpress site.
we don't use Composer ( I know we should) but some of the plugins do use Composer.
I don't know if these re interfering with our use of the autoload.php

```
require_once(TOOLS_ABSPATH . '/lib/paypal-php-library-release/autoload.php');

// Sample paypal-php-library-release/samples/classic/TransactionSearch.php
// **Classic  Works Great**
$PayPalConfig = array(
            'APIUsername'  => $api_username,
            'APIPassword'  => $api_password,
            'APISignature' => $api_signature, 
            'PrintHeaders' => false,
            'LogResults'   => $log_results,
            'LogPath'      => $log_path,
        );
// Create PayPal Object
$PayPalClassic = new angelleye\PayPal\PayPal($PayPalConfig);

$TSFields = array(
            'startdate' => $args['start_date' ], 
            'enddate' => $args['end_date' ],
);
$PayPalResult = $PayPalClassic->TransactionSearch($PayPalRequest);
```

Rest **cannot find Model**
`PHP Fatal error:  Uncaught Error: Class 'PayPal\Common\PayPalModel' not found in /.../wp-content/plugins/my-tools/lib/paypal-php-library-release/src/angelleye/PayPal/RestClass.php:44`
```
// Sample paypal-php-library-release/samples/rest/payment/ListPayments.php

// Create PayPal Object
        $configArray = array(
            'Sandbox'      => $sandbox,
            'ClientID'     => $clientId,  // ID and Secret worked with PayPal SDK test
            'ClientSecret' => $clientSecret,
            'LogResults'   => $log_results,
            'LogPath'      => $log_path,
        );

        $PayPalRest = new angelleye\PayPal\rest\payments\PaymentAPI($configArray);

```
ASD

**Comment by devchristina2** [comment]
Hi @dan-lutd,

Thank you for reaching out and submitting an issue on our GitHub repository.

We wanted to inform you that we’ve temporarily paused active support for this repository and will close all open issues, including this one. If you require further assistance or have additional questions, please submit a support ticket through our [Help Center](https://angelleye.atlassian.net/servicedesk/customer/portals), where our support team will be happy to assist you.

We appreciate your understanding and apologize for any inconvenience. Thank you for being part of our community!

Thanks, Christina.
