### ISSUE TITLE
Using vault credit card token is no longer supported?

### ISSUE THREAD

**Issue by vicn1222** [angelleye/paypal-php-library#214]
Can't use saved credit card id. It complains
"Funding Instrument Details are missing or Funding instrument not supported. Only credit-card is supported." 

What do I do wrong?

Code like below:

    $cc_token = new CreditCardToken;
    $cc_token->setCreditCardId( 'CARD-1MW2093014463931AMCVFLJI' );

    $fundingInstrument = new FundingInstrument();
    $fundingInstrument->setCreditCardToken( $cc_token );
 
    $payerInfo = createPayerInfo( ...... );

    $payer = new Payer();
    $payer->setPaymentMethod( 'credit_card' );

    $payer->setPayerInfo( $payerInfo );
    $payer->setFundingInstruments( array( $fundingInstrument ) );

**Comment by devchristina2** [comment]
Hi @vicn1222,

Thank you for reaching out and submitting an issue on our GitHub repository.

We wanted to inform you that we’ve temporarily paused active support for this repository and will close all open issues, including this one. If you require further assistance or have additional questions, please submit a support ticket through our [Help Center](https://angelleye.atlassian.net/servicedesk/customer/portals), where our support team will be happy to assist you.

We appreciate your understanding and apologize for any inconvenience. Thank you for being part of our community!

Thanks, Christina.
