### ISSUE TITLE
Class "PayPal\Common\PayPalModel" not found after Composer installation

### ISSUE THREAD

**Issue by cdasa** [angelleye/paypal-php-library#215]
Hi, 

I am aware that this issue has popped up in the past and the only solution presented was to install the library using composer. This did not solve the problem for me. 

All the directories are in order and all the files are properly referenced yet the issue persists. 

Here's a snippet of the code from "vendor\angelleye\paypal-php-library\src\angelleye\PayPal\RestClass.php" which generates the fatal error on line 44:

```
use PayPal\Common\PayPalModel;

/**
 * RestClass
 * This class includes the common configuration functions for the REST APIs bridge classes.
 *
 * @package 		paypal-php-library
 * @author			Andrew Angell <service@angelleye.com>
 */

class RestClass extends PayPalModel // FATAL ERROR HERE
{
    /**
     * Private vairable to fetch and return @PayPal\Rest\ApiContext object.
     *
     * @var \PayPal\Rest\ApiContext $_api_context 
     */
```
Nothing seems to be working without this PayPalModel class, not even the demos.

Here's what my directory setup looks like. It is as it should be. 

![Image 003](https://user-images.githubusercontent.com/91106297/219547311-dd860a77-71c7-4ff9-b238-11f40f8d4223.png)

**Comment by devchristina2** [comment]
Hi @cdasa,

Thank you for reaching out and submitting an issue on our GitHub repository.

We wanted to inform you that we’ve temporarily paused active support for this repository and will close all open issues, including this one. If you require further assistance or have additional questions, please submit a support ticket through our [Help Center](https://angelleye.atlassian.net/servicedesk/customer/portals), where our support team will be happy to assist you.

We appreciate your understanding and apologize for any inconvenience. Thank you for being part of our community!

Thanks, Christina
