### ISSUE TITLE
Still supported?

### ISSUE THREAD

**Issue by ponasromas** [angelleye/paypal-php-library#216]
Does this library still supported by maintainer?

**Comment by devchristina2** [comment]
Hi @ponasromas,

Thank you for reaching out and submitting an issue on our GitHub repository.

We wanted to inform you that we’ve temporarily paused active support for this repository and will close all open issues, including this one. If you require further assistance or have additional questions, please submit a support ticket through our [Help Center](https://angelleye.atlassian.net/servicedesk/customer/portals), where our support team will be happy to assist you.

We appreciate your understanding and apologize for any inconvenience. Thank you for being part of our community!

Thanks, Christina.
