### ISSUE TITLE
PHP 8.2.x error: Creation of dynamic property angelleye\\PayPal\\PayPal::$api_url is deprecated

### ISSUE THREAD

**Issue by ferrerjp** [angelleye/paypal-php-library#217]
In 8.2.x, I get errors starting here:

PayPal.php:

Line 84:  $this->api_url = 'https://gtctgyk7fh.execute-api.us-east-2.amazonaws.com/default/PayPalPaymentsTracker';

Creation of dynamic property angelleye\\PayPal\\PayPal::$api_url is deprecated

Changed to 8.1.x and it works again.

Will there be an update for 8.2?

**Comment by devchristina2** [comment]
Hi @ferrerjp,

Thank you for reaching out and submitting an issue on our GitHub repository.

We wanted to inform you that we’ve temporarily paused active support for this repository and will close all open issues, including this one. If you require further assistance or have additional questions, please submit a support ticket through our [Help Center](https://angelleye.atlassian.net/servicedesk/customer/portals), where our support team will be happy to assist you.

We appreciate your understanding and apologize for any inconvenience. Thank you for being part of our community!

Thanks, Christina.
