### ISSUE TITLE
Code improvements.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-php-library#36]
Hi Andrew,

Congratulations on the new class, I am using it on codeigniter and works perfectly.

I would like to suggest a small change

Replace (end of function MaskAPIResult($api_result))

```
    $api_result = '';
    foreach($api_result_array as $var => $val)
    {
        $api_result .= $var.'='.$val.'&';    
    }

    $api_result_length = strlen($api_result);
    $api_result = substr($api_result,0,$api_result_length-1);
```

for

$api_result  = http_build_query($api_result_array);

I do believe that you could replace many of the foreach loops that you have on this class with the http_build_query, as the foreach usage is to create the url to send to paypal.

I used to use the same method until I found this php function.

All the best,
Hortênsio

**Comment by angelleye** [comment]
Another guy saying the same thing along with another tip.
===========
Great tut. I just started reading through this and noticed a could code optimizations you could probably make. Instead of the foreach loop to build the parameter string:
$nvp_string = '';
foreach($request_params as $var=>$val)
{
$nvp_string .= '&'.$var.'='.urlencode($val);
}
Couldn't you just do:
$nvp_string = http_build_query($request_params);

?
and then instead of that whole parsing function ( function NVPToArray($NVPString) ), couldn't you just pass an array variable as the second parameter to parse_str() to fill with data?
parse_str($result, $proArray);

And now $proArray is an associative array holding the response data. Bare in mind i am just reading through this now, and i haven't fully tested this against the API yet, but those are just some nit picky things that could probably save you a few lines of code :)

**Comment by keyurptl** [comment]
Hi @angelleye 
With **http_build_query($api_result_array)**, it gives output similar to this because we are adding special character '*' here.

> USER=%2A%2A%2A%2A%2A&PWD=%2A%2A%2A%2A%2A&VERSION=119.0&BUTTONSOURCE=AngellEYE_PHPClass&SIGNATURE=%2A%2A%2A%2A%2A&METHOD=GetExpressCheckoutDetails&TOKEN=

so to overcome this and give output same as before
I have added this  **$api_result=urldecode(http_build_query($api_result_array));**
This gives output as 

> USER=*****&PWD=*****&VERSION=119.0&BUTTONSOURCE=AngellEYE_PHPClass&SIGNATURE=*****&METHOD=GetExpressCheckoutDetails&TOKEN=

**Comment by angelleye** [comment]
@keyurptl Did you look into doing the same for all the functions in the library?  Looks like you only did this in the masking functions..??

I know that's what the original user specifically referred to, but as he mentioned, the same thing could probably be done throughout the entire library as we've followed that foreach() pattern pretty much everywhere.

Please let me know your thoughts on this (is it really necessary...would it have a noticeable increase in performance..??).  Also let me know how long you think it would take to update everywhere.

**Comment by keyurptl** [comment]
Only this function and Payflowmask function works same.
I have changed in both functions.
There is no other masking functions in the library.
And yes sure it will increase performance.

**Comment by angelleye** [comment]
@keyurptl Right, there aren't any other "masking" functions, but the point is this same thing is happening in pretty much every function that the library has in it.  If this will increase performance, we should do it through-out the whole library.

For example, the [DoCapture() functions has it](https://github.com/angelleye/paypal-php-library/blob/dev/src/angelleye/PayPal/PayPal.php#L1036-L1039), and so does pretty much every single function.  

If it's worth it, we should fix it everywhere.

**Comment by keyurptl** [comment]
@angelleye ,We required this loop as this function do **strtoupper** for key of array that is main for the request.
So we required Foreach loop in that type of functions that's why i don't think to setup htttp_build_query function use there.

**Comment by angelleye** [comment]
Ok, gotcha.  Thanks.
