### ISSUE TITLE
On console : 'ErrorException' with message 'Undefined index: SERVER_PORT' in angelleye/paypal-php-library/src/angelleye/PayPal/PayPal.php:80

### ISSUE THREAD

**Issue by rtconner** [angelleye/paypal-php-library#52]
On console : 'ErrorException' with message 'Undefined index: SERVER_PORT' in angelleye/paypal-php-library/src/angelleye/PayPal/PayPal.php:80

Console scripts don't have a $_SERVER['SERVER_PORT'] variable.

**Comment by angelleye** [comment]
What version of PHP are you running? SERVER_PORT is indeed valid.

**Comment by rtconner** [comment]
"In console". Console scripts.

Read the PHP docs : http://php.net/manual/en/reserved.variables.server.php

> You may or may not find any of the following elements in $_SERVER. Note that few, if any, of these will be available (or indeed have any meaning) if running PHP on the command line.

**Comment by angelleye** [comment]
Ah, gotcha.  I've added that to my 2.0.4 planned release.  I'll make an adjustment to account for that.

**Comment by angelleye** [comment]
I made a small adjustment to check that SERVER_PORT is set prior to attempting to use it.  This should resolve the issue you were having.
