### ISSUE TITLE
PHP Notices

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-php-library#54]
Refer to #48 

>This change caused our app to start launching "Undefined index: Account Id" messages. It would have been better to check those variables with empty() instead of comparing with != '' to avoid non desired notices when the Account Id wasn't sent, specially in this case that it was added in a minor version change

**Comment by keyurptl** [comment]
In #48 , There is mentioned to use empty function.
So Do we need to add that condition for all the class variables ?
@angelleye
