### ISSUE TITLE
Demo kits - Express Checkout In-Context Sample

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-php-library#56]
https://developer.paypal.com/docs/classic/express-checkout/in-context/

**Comment by angelleye** [comment]
We need to review the documentation for In Context to see if there is anything about our API calls in particular need to adjust.  I think it's only a matter of front-end adjustments.

Once we get that figured out, we need to include /samples/SetExpressCheckout-InContext.php that shows you how to set things up for a basic In Context experience.

**Comment by keyurptl** [comment]
we'll do this in a demo kit

**Comment by keyurptl** [comment]
Created this branch from #73

**Comment by keyurptl** [comment]
@angelleye 
In-context demo was wrong as I tested today  compare with REST/NVP demo structure.
So I have changed the demo code for in-context.

**Comment by angelleye** [comment]
I'm able to get up to DoExpressCheckoutPayment.php in the demo, but I get this:

![image](https://cloud.githubusercontent.com/assets/629241/26274165/cf51cc2a-3d08-11e7-8261-880ec334ef28.png)

**Comment by angelleye** [comment]
Looks like you commented out all my original static shopping cart session stuff and replaced it with Payments session, but that session array doesn't have the parameters that the shopping cart I had setup included, so that's causing these errors.

Need to discuss why you commented out my static shopping cart stuff.  Seems you steered off the normal path of my demos.

**Comment by angelleye** [comment]
I just noticed the comment that this was created from #73, which was created from other issue branches.  I'll go through that order to merge things and that might get rid of these errors, but even if it does we'll still need to re-visit what you've done here commenting out my shopping cart stuff and replacing it with these stand-alone Payments and OrderItems arrays.

**Comment by tejasm-itpath** [comment]
@angelleye 
I am not getting this type of errors and also I found some adjustments that I have fixed in this demo.

**Comment by angelleye** [comment]
@tejasm-itpath You still didn't do what I wanted here.  

The whole point of these demo kits is to show people how to work with a shopping cart.  That's why we start them all with the static $_SESSION['shopping_cart'].  You've simply removed that and used $_SESSION['Payments'] instead.

What we should have done here is keep $_SESSION['shopping_cart'] in place, and then use the values from it to populate a regular $Payments and $PaymentOrderItems array later, which then gets passed into the library.

What we have here now would be a little bit confusing to some people who don't understand what's going on.

**Comment by tejasm-itpath** [comment]
@angelleye 
Okay , I will take care of it in the next demos
