### ISSUE TITLE
Add a filter in Angelleye_PayPal constructor's constructor

### ISSUE THREAD

**Issue by lordspace** [angelleye/paypal-php-library#57]
Hi,

Will it be possible to add a filter in the first line of the Angelleye_PayPal constructor that's in /plugins/paypal-for-woocommerce/classes/lib/angelleye/paypal-php-library/includes/paypal.class.php ?
You can make it all lowercase if you want.

```
$DataArray = apply_filters( 'Angelleye_PayPal_Construct_Params', $DataArray );
```

I am working on a client project and I need to switch between different paypal accounts based on certain conditions.

```
class Angelleye_PayPal
{

	var $APIUsername = '';
	var $APIPassword = '';
	var $APISignature = '';
	var $APISubject = '';
	var $APIVersion = '';
	var $APIButtonSource = '';
	var $APIMode = '';
	var $EndPointURL = '';
	var $Sandbox = '';
	var $PathToCertKeyPEM = '';
	var $SSL = '';
	
	/**
	 * Constructor
	 *
	 * @access	public
	 * @param	array	config preferences
	 * @return	void
	 */
	function __construct($DataArray)
	{
        $DataArray = apply_filters( 'Angelleye_PayPal_Construct_Params', $DataArray );
		
			................................
```

**Comment by angelleye** [comment]
Rather than put it there I think I would probably put it in the settings so that you could set the values used in the settings page based on a filter.  Whatever the currently set value is would get passed to the PayPal library.  Sound like that would work for you?

**Comment by angelleye** [comment]
Moving this to the PayPal for WooCommerce repo.

**Comment by lordspace** [comment]
I have a separate plugin that has its own settings page where API credentials are set.
My plugin really needs that filter in order to do its work.
I'd hate to have to patch your plugin every time you push an update.

If there isn't a callback registered will just return the first array that is passed without any modification.

I picked that location because you instantiate the Paypal class multiple times in wc-gateway-paypal-express-angelleye.php and the best central place is the constructor.

**Comment by angelleye** [comment]
Any time it's called, though, we pass in the values that are set in the plugin settings page.  As long as you've filtered those values it should work the way you need shouldn't it?

**Comment by angelleye** [comment]
What you did seems simple enough, and it seems you've already done it and have it working the way you want in your own setup, is that right?  

I could go ahead and add it there in the official plugin, I guess.  I generally try to avoid making changes to the library but this one may be simple enough it doesn't bother me.

**Comment by lordspace** [comment]
Thank you!

**Comment by angelleye** [comment]
This has been completed in our next update branch:  https://github.com/angelleye/paypal-woocommerce/issues/242
