### ISSUE TITLE
PayFlow mask api credentials.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-php-library#59]
Need to create a mask function to be used when saving API logs for PayFlow.

Would need to always mask the user, password, vendor, partner, cc number, exp date, security code.

**Comment by angelleye** [comment]
We have a similar function in the PayPal Classic class already:  https://github.com/angelleye/paypal-php-library/blob/dev/src/angelleye/PayPal/PayPal.php#L955-L993

Just need to add something like that to PayFlow class.

**Comment by keyurptl** [comment]
[https://github.com/angelleye/paypal-php-library/commit/9768e668cbcb7715aac2cf86e97189650c143f1a](https://github.com/angelleye/paypal-php-library/commit/9768e668cbcb7715aac2cf86e97189650c143f1a)

Due to Mistyping I am Commenting here commit.
