### ISSUE TITLE
SetPaymentOptions is missing SenderOptions fields

### ISSUE THREAD

**Issue by heyitsfranklin** [angelleye/paypal-php-library#60]
According to https://developer.paypal.com/webapps/developer/docs/classic/api/adaptive-payments/SetPaymentOptions_API_Operation/, you can optionally include "addressOverride"  and "shippingAddress" fields in SenderOptions. However, angelleye/PayPal/Adaptive.php does not account for these fields. It never looks for them and never sends them to PayPal.

Can you please update the PHP libraries to include these fields? They are very important because it allows us to set a shipping address if we collect it before redirecting the user to PayPal.

In the meantime, is there another way for me to include these fields?

**Comment by angelleye** [comment]
I could have sworn I had those in there, but like you I'm not seeing them.  I guess I need to go through some of the calls and get them updated to match current API version with PayPal.

I'll get that done as soon as I can.  If you need it done immediately you may want to add them yourself for the time-being.  All you would need to do is follow the same format we did with the other parameters in the Adaptive.php class, and then add the same parameters to the arrays in the template file, too.

**Comment by heyitsfranklin** [comment]
Thanks @angelleye! I think I can wait a few days while I work out some other bugs with my application. Hopefully by then these libraries will be updated :)

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/PPCL-119
