### ISSUE TITLE
ALLOWNOTE = 0 has no effect unless wrapped in quotes

### ISSUE THREAD

**Issue by jimyaghi** [angelleye/paypal-php-library#61]
Line 5103 in PayPal.php tests for empty with != This means that any values we want to intentionally set to 0 (integer) are not sent. I think for most cases it's fine, but with ALLOWNOTE the default appears to be 1 rather than 0. Perhaps there are other instances where the default is not an empty value but where empty is a valid value. It's not a real bug but it's a little counter intuitive. i fixed it by replacing with !== in that line to test for an empty string so booleans and integers that cast to empty are not skipped.

**Comment by AlbinoDrought** [comment]
This affects many operations, including:

`function CallbackResponse($DataArray)` [here](https://github.com/angelleye/paypal-php-library/blob/dev/src/angelleye/PayPal/PayPal.php#L1626)

specifically:

`$CurrentOptionVal != ''`

If an entered shipping option has an amount equivalent to 0 (but not "0"), it will not be added to the query string.

A possible (global) fix could be:

`preg_replace("/([$][^ $]+)( != )[^;$?]+/g", "strlen($1) ", $contents_of_paypal_php);`

**Comment by angelleye** [comment]
Thanks for the feedback.  I've been focused on our WordPress/WooCommerce plugins for a while, but I'll be doing another update on this before too long and will be sure to address this.

**Comment by keyurptl** [comment]
I am not getting for ALLOWNOTE  , else I have checked ExpressCheckoutCallback.php page.

**Comment by angelleye** [comment]
@keyurptl This isn't specific to the callback feature.  In general, our SetExpressCheckout template allows you to set the ALLOWNOTE parameter to enable notes or disable them during PayPal checkout.

According to @jimyaghi this is only working if you wrap the 0 in quotes for the value, which can be confusing.  It should actually work if any of these values are set...

* "0"
* 0
* "1"
* 1
* true
* "true"
* false
* "false"

**Comment by keyurptl** [comment]
Okay thanks @angelleye I got it.

**Comment by keyurptl** [comment]
AllowNote is actually deprecated
http://screencast.com/t/IzY66z1Js

**Comment by angelleye** [comment]
Ah, yes, I forgot about that.  We can just remove it from the templates / samples / class then.
