### ISSUE TITLE
Adaptive PaymentDetails only one reciever returned

### ISSUE THREAD

**Issue by powysm** [angelleye/paypal-php-library#62]
Just spotted that only the first receiver is being returned and not all of them which is the case when making a parallel payment. 
Love the lib otherwise ;-)

**Comment by angelleye** [comment]
Are you talking in a Pay response?

**Comment by powysm** [comment]
No after having made a pay request or completing the transaction, I am
hitting PaymentDetails $PayPal->PaymentDetails($PayPalRequestData);.

In the object returned there there is only one receiver being parsed from
the XML and not all of them.

Lines 930->935 of adaptive.php

**Comment by angelleye** [comment]
Ah, gotcha.  Thanks for pointing that out, I'll get it resolved.

Until then, the result does include the raw XML response, so you could parse anything you need to from that until I get the receivers included better.

**Comment by powysm** [comment]
Thanks

**Comment by devfelipereis** [comment]
Hello guys! I'm trying to pay to 3 people. I set one as primary and the others as normal receivers.
The primary is receiving all the money and the others nothing. 

I have something like this in one of my receivers:

` $Receiver = array(
            'Amount' => ($totalPrice*15)/100,                                            // Required.  Amount to be paid to the receiver.
            'Email' => 'somesandboxemail@gmail.com',                                                // Receiver's email address. 127 char max.
            'InvoiceID' => '',                                            // The invoice number for the payment.  127 char max.
            'PaymentType' => '',                                        // Transaction type.  Values are:  GOODS, SERVICE, PERSONAL, CASHADVANCE, DIGITALGOODS
            'PaymentSubType' => '',                                    // The transaction subtype for the payment.
            'AccountID' => '',
            'Phone' => array('CountryCode' => '', 'PhoneNumber' => '', 'Extension' => ''), // Receiver's phone number.   Numbers only.
            'Primary' => 'false'
        );`

That way, I think that this guy will receice 15% from total amount. As I said, I got no errors but when I log in with this user for example, I have nothing. But the primary one has received the total amount.

Am I missing something or we have an issue here? Thank you!

**Comment by angelleye** [comment]
What are you setting for the action type?  Sounds like you must be using PAY_PRIMARY when you should just use PAY.

**Comment by devfelipereis** [comment]
@angelleye Now it's working. You are correct, thank you!

**Comment by angelleye** [comment]
Glad to hear it!
