### ISSUE TITLE
Adaptive Payment Currency Conversion

### ISSUE THREAD

**Issue by keshav1990** [angelleye/paypal-php-library#65]
It's not giving me correct values

**Comment by keshav1990** [comment]
http://neowebsolution.com/currency/samples/

**Comment by angelleye** [comment]
Are you hitting the sandbox or live servers?  It seems to be working nicely here:  http://paypal.angelleye.com/paypal-php-library/samples/ConvertCurrency.php

I wonder if maybe it doesn't work well with 1.00.  Can you try another amount?

**Comment by keshav1990** [comment]
Not working again i am using Sandbox mode as i don't have appid for live and can you please tell me how can i get

**Comment by keshav1990** [comment]
https://www.paypal.com/in/cgi-bin/webscr?dispatch=5885d80a13c0db1f8e263663d3faee8d64ad11bbf4d2a5a1a0d303a50933f9b2
I need to make calculator like this

**Comment by keshav1990** [comment]
https://www.paypal.com/au/cgi-bin/webscr?cmd=_convert-currency-generic

**Comment by angelleye** [comment]
Can you provide the XML values that come back in $PayPalResult['XMLRequest'] and $PayPalResult['XMLResponse']?

**Comment by angelleye** [comment]
That last one you sent looks like it's showing different amounts.  Are you saying the conversion simply isn't accurate?

**Comment by keshav1990** [comment]
yes !!

    [XMLRequest] => <?xml version="1.0" encoding="utf-8"?><ConvertCurrencyRequest xmlns="http://svcs.paypal.com/types/ap"><requestEnvelope xmlns=""><detailLevel>ReturnAll</detailLevel><errorLanguage>en_US</errorLanguage></requestEnvelope><baseAmountList xmlns=""><currency xmlns=""><code xmlns="">USD</code><amount xmlns="">1</amount></currency></baseAmountList><convertToCurrencyList xmlns=""><currencyCode xmlns="">USD</currencyCode><currencyCode xmlns="">CAD</currencyCode></convertToCurrencyList></ConvertCurrencyRequest>
    [XMLResponse] => <?xml version='1.0' encoding='UTF-8'?><ns2:ConvertCurrencyResponse xmlns:ns2="http://svcs.paypal.com/types/ap"><responseEnvelope><timestamp>2016-02-06T10:19:41.314-08:00</timestamp><ack>Success</ack><correlationId>6dac8aa592c4c</correlationId><build>17820627</build></responseEnvelope><estimatedAmountTable><currencyConversionList><baseAmount><code>USD</code><amount>1</amount></baseAmount><currencyList><currency><code>USD</code><amount>1.00</amount></currency><currency><code>CAD</code><amount>1.00</amount></currency></currencyList></currencyConversionList></estimatedAmountTable></ns2:ConvertCurrencyResponse>

**Comment by keshav1990** [comment]
Compare the exchange rate 

https://www.paypal.com/au/cgi-bin/webscr?cmd=_convert-currency-generic
From api and from website you will see the difference

**Comment by angelleye** [comment]
It's possible the sandbox isn't accurate.  I guess I've never studied it that closely.  I would go ahead and get a live app together and see if you still have the same problem there.

**Comment by keshav1990** [comment]
And can you please guide me how can i get the live app ID to use in our application

**Comment by keshav1990** [comment]
Application id , i am not able to find any where 

ApplicationID

**Comment by angelleye** [comment]
Go to http://developer.paypal.com and login with your PayPal account.  Then click Dashboard and scroll down to this section:

![image](https://cloud.githubusercontent.com/assets/629241/12868784/8ce4fde0-ccd3-11e5-8772-4ca33a17247e.png)

Click the link to create an app.

**Comment by keshav1990** [comment]
Thanks Alot My friend it's working with live credentials 

http://neowebsolution.com/currency/samples/

**Comment by angelleye** [comment]
Glad to hear it!
