### ISSUE TITLE
Empty string supplied as input

### ISSUE THREAD

**Issue by devfelipereis** [angelleye/paypal-php-library#66]
Hello!

I was testing my app in my local env and everything was working fine until I upload files to server. 
When I try to pay something I get this error:

```
ErrorException in Adaptive.php line 403:
DOMDocument::loadXML(): Empty string supplied as input
```

Server is PHP 5.6 and have cURL enabled.

Any ideias? Thank you!

**Comment by angelleye** [comment]
Sounds like the server you uploaded to needs to have the software stack updated.  

Please take a look at [this post about POODLE](https://www.angelleye.com/paypal-ssl-error-poodle-vulnerability/) and then let me know if you have any specific questions.
