### ISSUE TITLE
GetVerifiedStatus accountIdentifier mobilePhoneNumber field

### ISSUE THREAD

**Issue by HostFat** [angelleye/paypal-php-library#67]
Are you thinking about adding the support to the accountIdentifier.mobilePhoneNumber field?

https://developer.paypal.com/docs/classic/api/adaptive-accounts/GetVerifiedStatus_API_Operation/

**Comment by angelleye** [comment]
Yes, I'll be doing an overall review of new things since I last updated and get them applied before long.

**Comment by keyurptl** [comment]
@angelleye  For this issue, I have reviewed GetVerifiedStatus.php.
Do we need to add accountIdentifier.mobilePhoneNumber field and accountIdentifier.emailAddress field?

**Comment by angelleye** [comment]
Yes, according to @HostFat we did not get those parameters included.  We need to add them to our template/sample and make sure that it's getting included in the actual class file that builds the request, of course.

**Comment by angelleye** [comment]
@keyurptl What you did here is not correct.  We should review this together so that I can explain where you went wrong here.

**Comment by tejasm-itpath** [comment]
@angelleye  Sure. We can discuss on this.

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/PPCL-118
