### ISSUE TITLE
Demo for Express Checkout - Parallel Payments 

### ISSUE THREAD

**Issue by keyurptl** [angelleye/paypal-php-library#71]
Move  Express Checkout - Parallel Payments demo from paypal-php-library-demo to paypal-php-library.

**Comment by keyurptl** [comment]
@angelleye ,
Creating this branch from #70 .

**Comment by angelleye** [comment]
@tejasm-itpath For parallel payments the idea is to show that the payment is being split between two different receivers.  You have used the same receiver account for both payments on this demo.  Please use these instead:

* paypal-facilitator@angelleye.com
* sandbox-seller@angelleye.com

**Comment by angelleye** [comment]
@tejasm-itpath I have made quite a few adjustments to this one to better demonstrate the way a split payment works.  

You did not have any shipping/handling/tax being included on this, so I added that in a way that splits it among the two receivers.

**Comment by tejasm-itpath** [comment]
@angelleye  I will look into the code for my own understanding :)

**Comment by dyanakiev** [comment]
Could this work this way:

Process:
1. Cart item book1 10$ + 2 booking fee
2. Click pay -> open paypal site -> buyer pays
3. When paying 10$ go to one email, 2$ go to another?

**Comment by angelleye** [comment]
@dyanakiev  Yes, but keep in mind the buyer would see that split during checkout.
