### ISSUE TITLE
Adaptive Payments - Header Update

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-php-library#74]
In our Adaptive Payments class, within the BuildHeaders method, we're including the following parameter:  X-PAYPAL-SECURITY-VERSION.

Looking at [this documentation](https://developer.paypal.com/docs/classic/adaptive-payments/integration-guide/APCallsHeadersAndPaymentTypes/), it seems this is supposed to be X-PAYPAL-SERVICE-VERSION, and would default to the current API version if not passed.

Since we're using the wrong header name I think it's just getting ignored.  We should update this to use the correct name, and run tests to ensure it doesn't cause errors, of course.

**Comment by keyurptl** [comment]
Created from dev branch.

**Comment by angelleye** [comment]
@keyurptl What you did was what I asked here, but I think I was simply wrong with my request.  Looking at the documentation again, it seems the best thing to do here would be to just leave this header out altogether.
