### ISSUE TITLE
Can matchCriteria NONE in GetVerifiedStatus API call ?

### ISSUE THREAD

**Issue by dmahesh22** [angelleye/paypal-php-library#78]
As per [Paypal Doc's](https://developer.paypal.com/webapps/developer/docs/classic/api/adaptive-accounts/GetVerifiedStatus_API_Operation/) `matchCriteria` can be `NONE` only for for certain financial institutions, what does it mean ? With sending `firstName` & `lastName` empty values and `matchCriteria` as `NONE` in sandbox environment I'm getting expected response from API call, will this also work in live environment ?

**Comment by angelleye** [comment]
While it cannot be guaranteed, anything the sandbox is doing should be the same on the live servers.  The only thing I would make sure to check before hand is that your live app has all the same approvals that the sandbox app is using with your tests.  Just make sure they know all the different API calls you're making and they'll verify that it's all approved for your live app.

**Comment by dmahesh22** [comment]
@angelleye Thanks for your quick response. And one small doubt what are the advantages your paypal application over [authorized paypal](https://github.com/paypal) application ? Don't mind, just want to know the pros & cons of both apps, that's it.

**Comment by angelleye** [comment]
Ours is typically easier to understand for people and quicker to use.  We're about to release a 3.0.0 update that's going to tie all of the REST APIs in as well.

So the general idea is that regardless of whether you want to use the Classic APIs (ie. NVP/SOAP, Adaptive Payments, Payments Pro, etc.), or the REST APIs you'll be able to just fill out some basic PHP arrays for data and it will handle the rest.
