### ISSUE TITLE
Remove closing PHP tags from scripts.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-php-library#79]
I've noticed that we're including the closing ?> tag in many of our classes/templates/samples.  This is not a good practice and it needs to be removed.

**Comment by keyurptl** [comment]
created this issue from Issue-77

**Comment by angelleye** [comment]
Looks like we still need to remove the ending tag from all of the original samples/templates/classes/etc.  I think you only removed it from your new stuff.
