### ISSUE TITLE
Demo for Express Checkout - Redeemed Offers

### ISSUE THREAD

**Issue by keyurptl** [angelleye/paypal-php-library#80]

**Comment by keyurptl** [comment]
created from #77

**Comment by keyurptl** [comment]
@angelleye 
It is working as basic demo 
Whenever we get details of wallet and instrument in sandbox buyer user then we check for that.

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/PPCL-116
