### ISSUE TITLE
API version issue.

### ISSUE THREAD

**Issue by keyurptl** [angelleye/paypal-php-library#81]
We have done some changes in #74 in Paypal.php API Version.
After setting value **1.0.0**
`$this->APIVersion = isset($DataArray['APIVersion']) ? $DataArray['APIVersion'] : '1.0.0';`
**Demos gives error (Error Code: 10400).**
While setting value to 119.0 in that line of Paypal.php demo works perfect and **samples gives error
**Service version 119.0 is unsupported****
Not all the samples gives errors
Invoice related samples gives errors. Express checkout still works with that.
See below output for sample code.
```
Array
(
    [Errors] => Array
        (
            [0] => Array
                (
                    [Receiver] => 
                    [Category] => Request
                    [Domain] => CoreRuntime
                    [ErrorID] => 2022
                    [ExceptionID] => 
                    [Message] => Service version 119.0 is unsupported
                    [Parameter] => 119.0
                    [Severity] => Error
                    [Subdomain] => Inbound_Meta_Data
                )

        )

    [Ack] => Failure
    [Build] => 28382006
    [CorrelationID] => b12969e35e0ee
    [Timestamp] => 2017-01-25T04:56:04.398-08:00
    [Count] => 
    [Page] => 
    [HasNextPage] => 
    [HasPreviousPage] => 
    [Invoices] => Array
        (
        )

    [XMLRequest] => ReturnAllen_UStejasm-merchant@itpathsolutions.co.in11
    [XMLResponse] => 2017-01-25T04:56:04.398-08:00Failureb12969e35e0ee283820062022CoreRuntimeInbound_Meta_DataErrorRequestService version 119.0 is unsupported119.0
)
```

**Comment by keyurptl** [comment]
@angelleye 
I have checked this in my new branch #dev_itpath which has everything up to date till now.

**Comment by angelleye** [comment]
In #74 I simply removed the header altogether.  Not sure if we need to do anything here now or if we can just close this issue..??

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/PPCL-115
