### ISSUE TITLE
PayFlow Log Adjustment

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-php-library#82]
The PayFlow request log is getting a little bit messed up.  The PayFlow raw NVP string includes the character count for the value being passed into each parameter, for example:

`AMT[5]=10.00`

We are using an NVPToArray() function to generate an array that gets dumped out in the log file along with the raw NVP string.  This function is not working well with the character counts included in the parameter names, so the result is something like this in the log...

```
BUTTONSOURCE[18]=AngellEYE_PHPClass&VERBOSITY[4]=HIGH&USER=*****&VENDOR=*****&PARTNER=*****&PWD=*****&TENDER[1]=C&TRXTYPE[1]=S&ACCT=*****&EXPDATE=*****&AMT[5]=10.00&FREIGHTAMT[4]=5.00&TAXAMT[4]=2.50&COMMENT1[15]=This is a test!&COMMENT2[20]=This is only a test!&CVV2=*****&BILLTOEMAIL[22]=sandbox@testdomain.com&BILLTOPHONENUM[12]=816-555-5555&BILLTOFIRSTNAME[6]=Tester&BILLTOLASTNAME[9]=Testerson&BILLTOSTREET[13]=123 Test Ave.&BILLTOCITY[11]=Kansas City&BILLTOSTATE[2]=MO&BILLTOZIP[5]=64111&BILLTOCOUNTRY[2]=US&SHIPTOFIRSTNAME[6]=Tester&SHIPTOLASTNAME[9]=Testerson&SHIPTOSTREET[13]=123 Test Ave.&SHIPTOCITY[11]=Kansas City&SHIPTOSTATE[2]=MO&SHIPTOZIP[5]=64111&SHIPTOCOUNTRY[2]=US

Array
(
    [BUTTONSOURCE] => Array
        (
            [18] => AngellEYE_PHPClass
        )

    [VERBOSITY] => Array
        (
            [4] => HIGH
        )

    [USER] => *****
    [VENDOR] => *****
    [PARTNER] => *****
    [PWD] => *****
    [TENDER] => Array
        (
            [1] => C
        )

    [TRXTYPE] => Array
        (
            [1] => S
        )

    [ACCT] => *****
    [EXPDATE] => *****
    [AMT] => Array
        (
            [5] => 10.00
        )

    [FREIGHTAMT] => Array
        (
            [4] => 5.00
        )

    [TAXAMT] => Array
        (
            [4] => 2.50
        )

    [COMMENT1] => Array
        (
            [15] => This is a test!
        )

    [COMMENT2] => Array
        (
            [20] => This is only a test!
        )

    [CVV2] => *****
    [BILLTOEMAIL] => Array
        (
            [22] => sandbox@testdomain.com
        )

    [BILLTOPHONENUM] => Array
        (
            [12] => 816-555-5555
        )

    [BILLTOFIRSTNAME] => Array
        (
            [6] => Tester
        )

    [BILLTOLASTNAME] => Array
        (
            [9] => Testerson
        )

    [BILLTOSTREET] => Array
        (
            [13] => 123 Test Ave.
        )

    [BILLTOCITY] => Array
        (
            [11] => Kansas City
        )

    [BILLTOSTATE] => Array
        (
            [2] => MO
        )

    [BILLTOZIP] => Array
        (
            [5] => 64111
        )

    [BILLTOCOUNTRY] => Array
        (
            [2] => US
        )

    [SHIPTOFIRSTNAME] => Array
        (
            [6] => Tester
        )

    [SHIPTOLASTNAME] => Array
        (
            [9] => Testerson
        )

    [SHIPTOSTREET] => Array
        (
            [13] => 123 Test Ave.
        )

    [SHIPTOCITY] => Array
        (
            [11] => Kansas City
        )

    [SHIPTOSTATE] => Array
        (
            [2] => MO
        )

    [SHIPTOZIP] => Array
        (
            [5] => 64111
        )

    [SHIPTOCOUNTRY] => Array
        (
            [2] => US
        )

)
```

This makes it looks like we're passing array data in to the request somehow, but it's really just seeing those character counts and treating it like an array.  The values are matching up, but it creates a messy log file.

**Comment by keyurptl** [comment]
[02232017_1256_56_AM_PayFlowRequest.txt](https://github.com/angelleye/paypal-php-library/files/795733/02232017_1256_56_AM_PayFlowRequest.txt)
[02232017_1256_56_AM_PayFlowResponse.txt](https://github.com/angelleye/paypal-php-library/files/795734/02232017_1256_56_AM_PayFlowResponse.txt)

**Comment by keyurptl** [comment]
This will looks like this @angelleye

**Comment by keyurptl** [comment]
[https://github.com/angelleye/paypal-php-library/commit/341fb23feea47b273a78dab9ba9e687b28696a25](https://github.com/angelleye/paypal-php-library/commit/341fb23feea47b273a78dab9ba9e687b28696a25)

Please check this commit,
I have committed in the issue-82 branch but by mistake I wrote 83 there. @angelleye

**Comment by angelleye** [comment]
@tejasm-itpath It looks like all you did here was remove the character count from the API request string altogether..??  This is not what we wanted to do here.  The request as it is sent to PayFlow should still include the character counts on the parameter names, but we need the log to display properly.

So we could just remove the character counts from the log before it prints out the array structure, but we need to make sure the raw data sent to PayFlow still includes it.

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/PPCL-114
