### ISSUE TITLE
Confused with what Credentials set to use

### ISSUE THREAD

**Issue by dmahesh22** [angelleye/paypal-php-library#84]
Hi,

 As mentioned in [this](https://github.com/paypal/sdk-core-php/wiki/Configuring-the-SDK) link, what I understood is we have to set API credentials for `acct1`, `acct2`, `acct3`. For me confusion is, `acct1` and `acct2` sets are replaceable? i,e. I have to configure either of two sets or both are mandatory ?. In `Sandbox` mode without setting `acct2` values I'm authenticated. What about in `live` mode and can I use same `cacert.pem` file in for `live` mode too ?

Thanks in advance.

**Comment by angelleye** [comment]
I'm a bit confused about what you're asking me here.  Are you asking about how to use the PayPal SDK, or are you trying to use ours as provided in this repo?

**Comment by dmahesh22** [comment]
@angelleye Sorry for making you confusion. I'm using PayPal SDK, though this question not belongs to here. I just want to clarify from you by thinking, you might having enough knowledge on PayPal SDK.

**Comment by angelleye** [comment]
I would recommend you use our library instead.  In fact, many PayPal integration reps prefer our library as well.  It really makes things more simple.

**Comment by dmahesh22** [comment]
@angelleye Ya, I'm aware of that, but our client want us to use PayPal SDK, so we went with that. Did you have any idea about my question ?

**Comment by angelleye** [comment]
I'm sorry, but I cannot support their SDK here.  If you want to [submit an order for general consulting](https://www.angelleye.com/product/paypal-help/) we could go that route, or if you want to post a question on [StackOverflow](http://stackoverflow.com/questions/tagged/paypal) or the [PayPal developer forum](https://www.paypal-community.com/t5/Merchant-Integration-Technical/ct-p/mts) I could help you there as I'm going through my normal routing of helping people.

**Comment by dmahesh22** [comment]
@angelleye Thanks for links and replies.
