### ISSUE TITLE
Demo Kit Sandbox Account Update

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-php-library#85]
The introduction to the demo kits tells people to use the following sandbox information as a buyer for testing:

Email:  paypalphp@angelleye.com
Password:  paypalphp

This sandbox account was killed in something that went wrong on PayPal's end, so we need to create a new sandbox account and update the information accordingly.

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/PPCL-112
