### ISSUE TITLE
520003 Authentication failed. API credentials are incorrect with sandbox accounts

### ISSUE THREAD

**Issue by amofbnow** [angelleye/paypal-php-library#87]
I'm getting an Authentication error trying to create a chained payment flow. I have already opened a question on stackoverflow where i place some code and details

[http://stackoverflow.com/questions/42809205/520003-authentication-failed-api-credentials-are-incorrect-with-sandbox-account](http://stackoverflow.com/questions/42809205/520003-authentication-failed-api-credentials-are-incorrect-with-sandbox-account)

**Comment by angelleye** [comment]
I commented on your SO thread.  I'm going to close this here and I can help you there.
