### ISSUE TITLE
Final Review of REST and all demo kits.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-php-library#90]
* Double check all REST samples / templates to ensure it's all organized well.
* Review all demo kits to ensure no errors are occurring in the demo, the download button works (or we might remove the download button, actually, on the paid kits), etc.
* Review comments, dates, etc. that may need updating.
* Update README files to add new features.
* Review demo kit descriptions on home page.
* Make sure BN code is passed in all REST calls:  AngellEYE_PHPClass  ([example](https://github.com/angelleye/paypal-woocommerce/blob/release/angelleye-includes/paypal-rest-api-utility.php#L324-L329))
* ~~Update sandbox account displayed for use in demos.  ( paypal-buyer@angelleye.com | paypalphp )~~

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/PPCL-110
