### ISSUE TITLE
Permission API Demo in Demo Kits

### ISSUE THREAD

**Issue by tejasm-itpath** [angelleye/paypal-php-library#92]
* https://www.angelleye.com/support/scp/tickets.php?id=1215

**Comment by tejasm-itpath** [comment]
I have follow this steps and i am getting success with it.
https://developer.paypal.com/docs/classic/permissions-service/ht_permissions-invoice/
I have following Issues with proper code format. 

1. Right now I have done it statically with the curl call directly adding into our demo, But we have to make it working with our library curl call and xml format too 
2. In the demo  I have added 2 new file PPAuth.php and AuthUtil.php, these both files are used for Oauth functionality, Either we have to make it separate classes  or we can add it with require_once.
3. In this Demo , We have done searchInvoice operation for the person who granted permission and with our API username pwd and signature we can get the  invoice details, we can set X-PAYPAL-AUTHORIZATION header with Adaptive Payment But we can not get TransactionDetails of the user if he granted too because it is in the PayPal.php which has no header in the request , I don't know exact reason about it.
May be some more questions will arise if we integrate more API with 3rd Party Permission.  

**Check The Attached file , that way I have done the code.**
[X-paypal-auth.txt](https://github.com/angelleye/paypal-php-library/files/1029147/X-paypal-auth.txt)

**Comment by tejasm-itpath** [comment]
@angelleye  Above are the issues I was talking about.

**Comment by tejasm-itpath** [comment]
For above comments , we will create separate demo kits. @angelleye

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/PPCL-108
