### ISSUE TITLE
3rd- Party Header setup in curl function for Permission API

### ISSUE THREAD

**Issue by tejasm-itpath** [angelleye/paypal-php-library#93]

**Comment by tejasm-itpath** [comment]
@angelleye 
SearchInvoices.php and SearchInvoicesThirdParty.php are two files in sample directory,
SearchInvoices.php is normal
SearchInvoicesThirdParty.php file is with token and token secret
**You should replace it with your token and token secret and email of the user while testing these files**

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/PPCL-107
