### ISSUE TITLE
some tipos

### ISSUE THREAD

**Issue by centurianii** [angelleye/paypal-php-library#96]
1. line PayPal.php:862 check is redundant as already passes as true in line 849. 
2. The same in: line PayPal.php:931 check is redundant as already passes as true in line 928. 
3. Function CURLRequest() at line 610 uses only 1st argument.
4. Class PayPal.php: added following properties before called by __construct() (just to be typical with OO):
var $Countries = '';
var $States = '';
var $AVSCodes = '';
var $CVV2Codes = '';
var $CurrencyCodes = '';
5. PhpDoc for function CallbackResponse($DataArray) at line 1613:
@return  mixed[]  Returns the raw request.

**Comment by angelleye** [comment]
Thanks, we'll make adjustments in our next update!

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/PPCL-105
