### ISSUE TITLE
Add an access level for all methods

### ISSUE THREAD

**Issue by halfer** [angelleye/paypal-php-library#98]
All class methods, including constructors, should have an access level. They are `public` by default, but it is considered good practice to be explicit. I believe there is a PSR guideline for this.

Methods that should not be called directly should be made `protected` or, in rare cases, `private`. For example, should `angelleye\PayPal\Financing::BuildHeaders($PrintHeaders = false)` ever be called from outside of the class?

There probably isn't any value in maintaining `@access	public` docblock entries, since IDEs can introspect the access level from the keywords instead. I would suggest these are deleted.

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/PPCL-103
