### ISSUE TITLE
Use an IDE to scan the library for unused parameters

### ISSUE THREAD

**Issue by halfer** [angelleye/paypal-php-library#99]
I just noticed this method:

```
function CURLRequest($Request = "", $APIName = "", $APIOperation = "", $PrintHeaders = false)
```

It looks like `$APIName` and `$APIOperation` are not used in [the body of the method](https://github.com/angelleye/paypal-php-library/blob/dev/src/angelleye/PayPal/Financing.php#L95) at all.

I use NetBeans, but PHPStorm and others will do this for you. There are probably some automated tools as well.

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/PPCL-102
